export const categories = [
  {id: 'finance', title: '금융/계산', icon: '💳'},
  {id: 'productivity', title: '생산성', icon: '⚡'},
  {id: 'dev', title: '개발자', icon: '💻'},
  {id: 'security', title: '보안/프라이버시', icon: '🛡️'},
  {id: 'lifestyle', title: '생활/건강', icon: '🌿'},
  {id: 'utility', title: '유틸리티', icon: '🛠️'},
  {id: 'design', title: '디자인/콘텐츠', icon: '✨'},
  {id: 'performance', title: '성능/모니터링', icon: '🚀'},
  {id: 'text', title: '텍스트/문서', icon: '📝'},
  {id: 'css', title: 'CSS/프론트엔드', icon: '🎨'},
  {id: 'random', title: '랜덤/목록', icon: '🎲'},
  {id: 'time', title: '시간/일정', icon: '⏱️'},
]

export const tools = [
  {slug: 'percent-calculator', category: 'finance', type: 'percent', title: '퍼센트 계산기', description: '증가율, 감소율, 전체 대비 비율을 빠르게 계산합니다.'},
  {slug: 'vat-calculator', category: 'finance', type: 'vat', title: '부가세(VAT) 계산기', description: '공급가액과 부가세 포함 금액을 상호 계산합니다.'},
  {slug: 'tax33-calculator', category: 'finance', type: 'tax33', title: '원천징수 세금 계산기', description: '원하는 세율을 입력해 공제 전후 금액을 계산합니다.'},
  {slug: 'interest-calculator', category: 'finance', type: 'interest', title: '이자 계산기', description: '단리와 복리 기준의 예상 이자를 계산합니다.'},
  {slug: 'crypto-profit-calculator', category: 'finance', type: 'crypto', title: '코인 수익률 계산기', description: '매수가, 매도가, 수량으로 수익률을 계산합니다.'},
  {slug: 'area-converter', category: 'utility', type: 'area', title: '평수 ↔ ㎡ 변환기', description: '평과 제곱미터를 즉시 변환합니다.'},
  {slug: 'text-counter', category: 'productivity', type: 'text', title: '글자 수 및 바이트 계산기', description: '글자 수, 단어 수, 줄 수, UTF-8 바이트를 계산합니다.'},
  {slug: 'timezone-converter', category: 'productivity', type: 'timezone', title: '시간대 변환기', description: '주요 도시 시간대를 기준으로 시간을 비교합니다.'},
  {slug: 'pomodoro-timer', category: 'productivity', type: 'pomodoro', title: '뽀모도로 타이머', description: '집중 시간과 휴식 시간을 설정해 작업 리듬을 만듭니다.'},
  {slug: 'json-formatter', category: 'dev', type: 'json', title: 'JSON 포맷터', description: 'JSON을 검증하고 보기 좋게 정렬합니다.'},
  {slug: 'regex-tester', category: 'dev', type: 'regex', title: '정규표현식 테스터', description: '정규식 매칭 결과를 브라우저에서 바로 확인합니다.'},
  {slug: 'password-generator', category: 'security', type: 'password', title: '비밀번호 생성기', description: '길이와 문자 조합을 선택해 안전한 비밀번호를 생성합니다.'},
  {slug: 'redact-tool', category: 'security', type: 'redact', title: '개인정보 마스킹 도구', description: '이메일, 전화번호, 주민번호 형태의 민감 정보를 가립니다.'},
  {slug: 'url-checker', category: 'security', type: 'url', title: 'URL 안전 점검기', description: 'URL 형식과 의심 패턴을 로컬 규칙으로 점검합니다.'},
  {slug: 'burn-message', category: 'security', type: 'burn', title: '일회용 비밀 메모', description: '브라우저 안에서만 보관되는 임시 비밀 메모를 만듭니다.'},
  {slug: 'color-checker', category: 'design', type: 'color', title: '색상 팔레트/대비 검사기', description: 'HEX 색상과 텍스트 대비율을 확인합니다.'},
  {slug: 'font-compare', category: 'design', type: 'font', title: '다국어 폰트 비교기', description: '문장을 여러 시스템 폰트로 비교해봅니다.'},
  {slug: 'nickname-generator', category: 'design', type: 'nickname', title: '영문 성함/닉네임 추천기', description: '이름이나 키워드로 영문 닉네임 후보를 만듭니다.'},
  {slug: 'gpa-converter', category: 'lifestyle', type: 'gpa', title: '학점 변환기', description: '4.5, 4.3, 100점 기준 GPA를 상호 변환합니다.'},
  {slug: 'gym-plate-calculator', category: 'lifestyle', type: 'gym', title: '1RM & 바벨 원판 계산기', description: '예상 1RM과 바벨 한쪽 원판 구성을 계산합니다.'},
  {slug: 'pet-food-calculator', category: 'lifestyle', type: 'pet', title: '반려동물 사료량 계산기', description: '체중과 kcal 기준으로 하루 급여량을 계산합니다.'},
  {slug: 'coffee-yield-calculator', category: 'lifestyle', type: 'coffee', title: '커피 브루잉 수율 계산기', description: '원두, 추출액, TDS로 추출 수율을 계산합니다.'},
  {slug: 'sla-uptime-calculator', category: 'performance', type: 'sla', title: 'SLA 가동률 계산기', description: '가동률 기준 허용 장애 시간을 계산합니다.'},
  {slug: 'carbon-footprint-calculator', category: 'performance', type: 'carbon', title: '웹사이트 탄소 발자국 계산기', description: '페이지뷰와 전송량 기준 대략적인 CO2를 추정합니다.'},
  {slug: 'ttfb-tester', category: 'performance', type: 'ttfb', title: 'TTFB 기록 도구', description: '측정한 응답시간을 붙여 넣어 평균과 p95를 계산합니다.'},
  {slug: 'resistor-calculator', category: 'dev', type: 'resistor', title: '저항기 색띠 계산기', description: '4색 저항 색띠 값을 옴 단위로 계산합니다.'},
  {slug: 'construction-dictionary', category: 'utility', type: 'construction', title: '건설현장 용어 사전', description: '자주 쓰는 현장 용어와 표준 표현을 검색합니다.'},
  {slug: 'elbow-offset-calculator', category: 'utility', type: 'elbow', title: '배관 엘보 오프셋 계산기', description: '45도/90도 엘보 기준 절단 길이를 간단 계산합니다.'},
  {slug: 'case-converter', category: 'text', type: 'case', title: '대소문자 변환기', description: '문장을 대문자, 소문자, 제목형, 문장형으로 변환합니다.'},
  {slug: 'whitespace-remover', category: 'text', type: 'whitespace', title: '공백 정리 도구', description: '중복 공백과 빈 줄을 깔끔하게 정리합니다.'},
  {slug: 'lorem-ipsum-generator', category: 'text', type: 'lorem', title: 'Lorem Ipsum 생성기', description: '디자인 시안용 더미 텍스트를 생성합니다.'},
  {slug: 'markdown-preview', category: 'text', type: 'markdown', title: '마크다운 미리보기', description: '마크다운 문법을 간단한 HTML 미리보기로 확인합니다.'},
  {slug: 'csv-to-table', category: 'text', type: 'csv', title: 'CSV 테이블 뷰어', description: 'CSV 텍스트를 표 형태로 확인합니다.'},
  {slug: 'duplicate-line-remover', category: 'text', type: 'dedupe', title: '중복 줄 제거기', description: '목록에서 중복된 줄을 제거합니다.'},
  {slug: 'sort-lines', category: 'text', type: 'sort-lines', title: '줄 정렬 도구', description: '텍스트 줄을 가나다/알파벳 순서로 정렬합니다.'},
  {slug: 'text-diff', category: 'text', type: 'diff', title: '텍스트 차이 비교', description: '두 텍스트의 줄 단위 차이를 빠르게 비교합니다.'},
  {slug: 'url-slug-generator', category: 'dev', type: 'slug', title: 'URL 슬러그 생성기', description: '제목을 SEO 친화적인 URL 슬러그로 변환합니다.'},
  {slug: 'base64-encoder-decoder', category: 'dev', type: 'base64', title: 'Base64 인코더/디코더', description: '문자열을 Base64로 인코딩하거나 디코딩합니다.'},
  {slug: 'url-encoder-decoder', category: 'dev', type: 'url-codec', title: 'URL 인코더/디코더', description: 'URL 문자열을 안전하게 인코딩/디코딩합니다.'},
  {slug: 'html-encoder-decoder', category: 'dev', type: 'html-codec', title: 'HTML 엔티티 인코더/디코더', description: 'HTML 특수문자를 엔티티로 변환하거나 되돌립니다.'},
  {slug: 'html-minifier', category: 'dev', type: 'minify-html', title: 'HTML 압축기', description: 'HTML 코드의 불필요한 공백을 줄입니다.'},
  {slug: 'css-minifier', category: 'dev', type: 'minify-css', title: 'CSS 압축기', description: 'CSS 코드의 주석과 공백을 줄입니다.'},
  {slug: 'javascript-minifier', category: 'dev', type: 'minify-js', title: 'JavaScript 압축기', description: '간단한 JavaScript 공백과 주석을 줄입니다.'},
  {slug: 'jwt-decoder', category: 'dev', type: 'jwt', title: 'JWT 디코더', description: 'JWT 헤더와 페이로드를 로컬에서 디코딩합니다.'},
  {slug: 'uuid-generator', category: 'dev', type: 'uuid', title: 'UUID 생성기', description: '브라우저에서 UUID v4 값을 생성합니다.'},
  {slug: 'timestamp-converter', category: 'dev', type: 'timestamp', title: 'Unix 타임스탬프 변환기', description: 'Unix 시간과 날짜 문자열을 상호 변환합니다.'},
  {slug: 'css-gradient-generator', category: 'css', type: 'gradient', title: 'CSS 그라디언트 생성기', description: '두 색상으로 linear-gradient 코드를 만듭니다.'},
  {slug: 'box-shadow-generator', category: 'css', type: 'box-shadow', title: 'CSS 박스 섀도우 생성기', description: '미리보기를 보며 box-shadow 코드를 생성합니다.'},
  {slug: 'border-radius-generator', category: 'css', type: 'radius', title: 'CSS Border Radius 생성기', description: '모서리 둥글기 값을 CSS 코드로 만듭니다.'},
  {slug: 'css-clamp-generator', category: 'css', type: 'clamp', title: 'CSS clamp() 생성기', description: '반응형 폰트 크기 clamp 값을 계산합니다.'},
  {slug: 'aspect-ratio-calculator', category: 'css', type: 'aspect', title: '종횡비 계산기', description: '이미지와 영상의 비율 기반 크기를 계산합니다.'},
  {slug: 'hex-rgba-converter', category: 'design', type: 'hex-rgba', title: 'HEX ↔ RGBA 변환기', description: '색상 코드를 HEX와 RGBA 사이에서 변환합니다.'},
  {slug: 'color-mixer', category: 'design', type: 'color-mix', title: '색상 믹서', description: '두 색상을 단계별로 섞은 팔레트를 만듭니다.'},
  {slug: 'image-size-ratio', category: 'design', type: 'image-ratio', title: '이미지 리사이즈 비율 계산기', description: '원본 비율을 유지한 리사이즈 크기를 계산합니다.'},
  {slug: 'open-graph-generator', category: 'marketing', type: 'og', title: 'Open Graph 메타태그 생성기', description: 'SNS 공유용 OG 메타태그 코드를 생성합니다.'},
  {slug: 'utm-builder', category: 'marketing', type: 'utm', title: 'UTM 링크 빌더', description: '캠페인 추적용 UTM URL을 만듭니다.'},
  {slug: 'keyword-density', category: 'marketing', type: 'keyword-density', title: '키워드 밀도 계산기', description: '본문에서 특정 키워드의 등장 비율을 계산합니다.'},
  {slug: 'random-number-generator', category: 'random', type: 'random-number', title: '랜덤 숫자 생성기', description: '범위 내 무작위 숫자를 생성합니다.'},
  {slug: 'list-randomizer', category: 'random', type: 'list-random', title: '목록 랜덤 섞기', description: '줄 단위 목록을 무작위 순서로 섞습니다.'},
  {slug: 'team-randomizer', category: 'random', type: 'team', title: '팀 나누기 도구', description: '이름 목록을 원하는 팀 수로 나눕니다.'},
  {slug: 'dice-roller', category: 'random', type: 'dice', title: '주사위 굴리기', description: '여러 면체 주사위를 굴린 결과를 확인합니다.'},
  {slug: 'coin-flipper', category: 'random', type: 'coin', title: '동전 던지기', description: '앞면/뒷면을 무작위로 선택합니다.'},
  {slug: 'stopwatch', category: 'time', type: 'stopwatch', title: '스톱워치', description: '브라우저에서 간단히 시간을 측정합니다.'},
  {slug: 'countdown-timer', category: 'time', type: 'countdown', title: '카운트다운 타이머', description: '목표 분/초까지 남은 시간을 계산합니다.'},
  {slug: 'age-calculator', category: 'time', type: 'age', title: '만 나이 계산기', description: '생년월일 기준 만 나이를 계산합니다.'},
  {slug: 'business-day-calculator', category: 'time', type: 'business-day', title: '영업일 계산기', description: '두 날짜 사이 평일 수를 계산합니다.'},
  {slug: 'tip-calculator', category: 'finance', type: 'tip', title: '팁 계산기', description: '팁과 인원수 기준 1인당 금액을 계산합니다.'},
  {slug: 'discount-calculator', category: 'finance', type: 'discount', title: '할인율 계산기', description: '할인 후 가격과 절약 금액을 계산합니다.'},
  {slug: 'salary-converter', category: 'finance', type: 'salary', title: '시급/연봉 변환기', description: '시급, 주 근무시간, 연봉을 상호 계산합니다.'},
  {slug: 'fuel-cost-calculator', category: 'lifestyle', type: 'fuel', title: '주유비 계산기', description: '거리, 연비, 유가 기준 예상 주유비를 계산합니다.'},
  {slug: 'water-intake-calculator', category: 'lifestyle', type: 'water', title: '물 섭취량 계산기', description: '체중 기준 하루 권장 물 섭취량을 추정합니다.'},
  {slug: 'calorie-calculator', category: 'lifestyle', type: 'calorie', title: '기초대사량 계산기', description: '성별, 나이, 키, 체중 기준 BMR을 계산합니다.'},
  {slug: 'bmi-water-calculator', category: 'lifestyle', type: 'bmi-water', title: 'BMI & 물 섭취량 계산기', description: 'BMI와 물 섭취량을 함께 계산합니다.'},
  {slug: 'grocery-list', category: 'productivity', type: 'grocery', title: '장보기 목록 정리', description: '구매 목록을 체크 가능한 형태로 정리합니다.'},
  {slug: 'meeting-notes', category: 'productivity', type: 'meeting', title: '회의록 템플릿 생성기', description: '회의 제목과 안건으로 회의록 템플릿을 만듭니다.'},
  {slug: 'simple-notepad', category: 'productivity', type: 'notepad', title: '간단 메모장', description: '브라우저 안에서 빠르게 메모를 작성합니다.'},
  {slug: 'bar-chart-maker', category: 'utility', type: 'bar-chart', title: '막대 그래프 메이커', description: '라벨과 숫자를 입력해 간단한 막대 그래프를 만듭니다.'},
  {slug: 'pie-chart-calculator', category: 'utility', type: 'pie-chart', title: '파이 차트 비율 계산기', description: '항목별 비율과 각도를 계산합니다.'},
]

export const existingTools = [
  {slug: 'bmi-calculator', category: 'lifestyle', title: 'BMI 계산기', description: '체질량지수를 계산합니다.'},
  {slug: 'loan-calculator', category: 'finance', title: '대출 계산기', description: '대출 월 상환금을 계산합니다.'},
  {slug: 'dday-calculator', category: 'productivity', title: 'D-Day 계산기', description: '날짜까지 남은 일수를 계산합니다.'},
  {slug: 'unit-converter', category: 'utility', title: '단위 변환기', description: '길이, 무게, 온도를 변환합니다.'},
  {slug: 'qr-code-generator', category: 'utility', title: 'QR 코드 생성기', description: '텍스트와 URL을 QR 코드로 만듭니다.'},
]

const categoryLabels = {
  finance: 'Finance and calculators',
  productivity: 'Productivity',
  dev: 'Developer tools',
  security: 'Security and privacy',
  lifestyle: 'Lifestyle and health',
  utility: 'Everyday utilities',
  design: 'Design and content',
  performance: 'Performance',
  text: 'Text and documents',
  css: 'CSS and frontend',
  marketing: 'Marketing and SEO',
  random: 'Randomizers',
  time: 'Time and dates',
}

const categoryIcons = {
  finance: '💳',
  productivity: '⚡',
  dev: '💻',
  security: '🛡️',
  lifestyle: '🌿',
  utility: '🛠️',
  design: '✨',
  performance: '🚀',
  text: '📝',
  css: '🎨',
  marketing: '📣',
  random: '🎲',
  time: '⏱️',
}

const toolTitles = {
  'bmi-calculator': 'BMI calculator',
  'loan-calculator': 'Loan calculator',
  'dday-calculator': 'D-Day calculator',
  'unit-converter': 'Unit converter',
  'qr-code-generator': 'QR code generator',
  'percent-calculator': 'Percent calculator',
  'vat-calculator': 'Tax calculator',
  'tax33-calculator': 'Withholding tax calculator',
  'interest-calculator': 'Interest calculator',
  'crypto-profit-calculator': 'Crypto profit calculator',
  'area-converter': 'Area converter',
  'text-counter': 'Text and byte counter',
  'timezone-converter': 'Timezone converter',
  'pomodoro-timer': 'Pomodoro timer',
  'json-formatter': 'JSON formatter',
  'regex-tester': 'Regex tester',
  'password-generator': 'Password generator',
  'redact-tool': 'Personal data redactor',
  'url-checker': 'URL safety checker',
  'burn-message': 'One-time secret memo',
  'color-checker': 'Color contrast checker',
  'font-compare': 'Font comparison tool',
  'nickname-generator': 'Nickname generator',
  'gpa-converter': 'GPA converter',
  'gym-plate-calculator': '1RM and plate calculator',
  'pet-food-calculator': 'Pet food calculator',
  'coffee-yield-calculator': 'Coffee brew yield calculator',
  'sla-uptime-calculator': 'SLA uptime calculator',
  'carbon-footprint-calculator': 'Website carbon estimator',
  'ttfb-tester': 'TTFB log analyzer',
  'resistor-calculator': 'Resistor color code calculator',
  'construction-dictionary': 'Construction terms dictionary',
  'elbow-offset-calculator': 'Pipe elbow offset calculator',
  'case-converter': 'Case converter',
  'whitespace-remover': 'Whitespace cleaner',
  'lorem-ipsum-generator': 'Lorem ipsum generator',
  'markdown-preview': 'Markdown preview',
  'csv-to-table': 'CSV table viewer',
  'duplicate-line-remover': 'Duplicate line remover',
  'sort-lines': 'Line sorter',
  'text-diff': 'Text diff checker',
  'url-slug-generator': 'URL slug generator',
  'base64-encoder-decoder': 'Base64 encoder and decoder',
  'url-encoder-decoder': 'URL encoder and decoder',
  'html-encoder-decoder': 'HTML entity encoder and decoder',
  'html-minifier': 'HTML minifier',
  'css-minifier': 'CSS minifier',
  'javascript-minifier': 'JavaScript minifier',
  'jwt-decoder': 'JWT decoder',
  'uuid-generator': 'UUID generator',
  'timestamp-converter': 'Unix timestamp converter',
  'css-gradient-generator': 'CSS gradient generator',
  'box-shadow-generator': 'CSS box shadow generator',
  'border-radius-generator': 'CSS border radius generator',
  'css-clamp-generator': 'CSS clamp generator',
  'aspect-ratio-calculator': 'Aspect ratio calculator',
  'hex-rgba-converter': 'HEX and RGBA converter',
  'color-mixer': 'Color mixer',
  'image-size-ratio': 'Image resize ratio calculator',
  'open-graph-generator': 'Open Graph meta tag generator',
  'utm-builder': 'UTM link builder',
  'keyword-density': 'Keyword density calculator',
  'random-number-generator': 'Random number generator',
  'list-randomizer': 'List randomizer',
  'team-randomizer': 'Team randomizer',
  'dice-roller': 'Dice roller',
  'coin-flipper': 'Coin flipper',
  'stopwatch': 'Stopwatch',
  'countdown-timer': 'Countdown timer',
  'age-calculator': 'Age calculator',
  'business-day-calculator': 'Business day calculator',
  'tip-calculator': 'Tip calculator',
  'discount-calculator': 'Discount calculator',
  'salary-converter': 'Salary converter',
  'fuel-cost-calculator': 'Fuel cost calculator',
  'water-intake-calculator': 'Water intake calculator',
  'calorie-calculator': 'Calorie calculator',
  'bmi-water-calculator': 'BMI and water intake calculator',
  'grocery-list': 'Grocery list organizer',
  'meeting-notes': 'Meeting notes generator',
  'simple-notepad': 'Simple notepad',
  'bar-chart-maker': 'Bar chart maker',
  'pie-chart-calculator': 'Pie chart calculator',
}

const toolDescriptions = {
  'bmi-calculator': 'Calculate body mass index from height and weight.',
  'loan-calculator': 'Estimate monthly payments from loan amount, rate, and term.',
  'dday-calculator': 'Count the days remaining until, or passed since, a selected date.',
  'unit-converter': 'Convert common length, weight, and temperature units.',
  'qr-code-generator': 'Create a QR code image from text or a URL.',
  'percent-calculator': 'Calculate percentages, increases, decreases, and ratios.',
  'vat-calculator': 'Calculate tax amount and tax-included totals with a custom rate.',
  'tax33-calculator': 'Calculate before-tax and after-tax amounts with a custom withholding rate.',
  'interest-calculator': 'Estimate simple or compound interest over a chosen period.',
  'crypto-profit-calculator': 'Check crypto profit, loss, and return from buy and sell prices.',
  'area-converter': 'Convert quickly between pyeong and square meters.',
  'text-counter': 'Count characters, words, lines, and UTF-8 bytes.',
  'timezone-converter': 'Compare times across major cities and time zones.',
  'pomodoro-timer': 'Run focus and break sessions with a simple Pomodoro timer.',
  'json-formatter': 'Validate JSON and format it into a readable structure.',
  'regex-tester': 'Test regular expressions against sample text in the browser.',
  'password-generator': 'Generate strong passwords with custom length and character sets.',
  'redact-tool': 'Mask sensitive patterns such as emails and phone numbers.',
  'url-checker': 'Inspect a URL for formatting issues and suspicious local patterns.',
  'burn-message': 'Create a temporary secret note stored only in the browser.',
  'color-checker': 'Check color contrast and preview accessible text combinations.',
  'font-compare': 'Compare the same sentence across common system fonts.',
  'nickname-generator': 'Generate English nickname ideas from a name or keyword.',
  'gpa-converter': 'Convert GPA scores between 4.5, 4.3, and 100-point scales.',
  'gym-plate-calculator': 'Estimate one-rep max and calculate barbell plate loading.',
  'pet-food-calculator': 'Estimate daily pet food portions from weight and calories.',
  'coffee-yield-calculator': 'Calculate coffee extraction yield from dose, beverage, and TDS.',
  'sla-uptime-calculator': 'Convert SLA uptime targets into allowed downtime.',
  'carbon-footprint-calculator': 'Estimate website CO2 from page views and transfer size.',
  'ttfb-tester': 'Paste response-time logs to calculate average and p95 TTFB.',
  'resistor-calculator': 'Decode four-band resistor colors into resistance values.',
  'construction-dictionary': 'Search common construction-site terms and standard wording.',
  'elbow-offset-calculator': 'Calculate simple pipe elbow offsets for 45 and 90 degree bends.',
  'case-converter': 'Convert text between uppercase, lowercase, title case, and sentence case.',
  'whitespace-remover': 'Clean duplicate spaces, extra blank lines, and messy text spacing.',
  'lorem-ipsum-generator': 'Generate placeholder copy for layouts and mockups.',
  'markdown-preview': 'Preview Markdown as simple rendered HTML.',
  'csv-to-table': 'Turn CSV text into a readable table preview.',
  'duplicate-line-remover': 'Remove repeated lines from pasted lists.',
  'sort-lines': 'Sort text lines alphabetically or in reverse order.',
  'text-diff': 'Compare two blocks of text and highlight line differences.',
  'url-slug-generator': 'Convert headings into clean SEO-friendly URL slugs.',
  'base64-encoder-decoder': 'Encode text to Base64 or decode Base64 back to text.',
  'url-encoder-decoder': 'Encode or decode URL-safe text strings.',
  'html-encoder-decoder': 'Convert special characters to HTML entities and back.',
  'html-minifier': 'Reduce unnecessary whitespace in HTML code.',
  'css-minifier': 'Remove comments and extra whitespace from CSS.',
  'javascript-minifier': 'Lightly compact JavaScript by removing comments and spacing.',
  'jwt-decoder': 'Decode JWT headers and payloads locally.',
  'uuid-generator': 'Generate UUID v4 values in the browser.',
  'timestamp-converter': 'Convert Unix timestamps and date strings both ways.',
  'css-gradient-generator': 'Build linear-gradient CSS from two colors.',
  'box-shadow-generator': 'Tune a box-shadow visually and copy the CSS.',
  'border-radius-generator': 'Create CSS border-radius values for each corner.',
  'css-clamp-generator': 'Calculate responsive CSS clamp() font sizes.',
  'aspect-ratio-calculator': 'Calculate sizes from image or video aspect ratios.',
  'hex-rgba-converter': 'Convert colors between HEX and RGBA formats.',
  'color-mixer': 'Blend two colors into a stepped palette.',
  'image-size-ratio': 'Resize images while preserving the original aspect ratio.',
  'open-graph-generator': 'Generate Open Graph meta tags for social sharing.',
  'utm-builder': 'Build campaign tracking URLs with UTM parameters.',
  'keyword-density': 'Measure how often a keyword appears in body text.',
  'random-number-generator': 'Generate random numbers within a chosen range.',
  'list-randomizer': 'Shuffle pasted list items into a random order.',
  'team-randomizer': 'Split a list of names into a selected number of teams.',
  'dice-roller': 'Roll dice with different side counts and see the result.',
  'coin-flipper': 'Randomly choose heads or tails.',
  'stopwatch': 'Measure elapsed time with a simple browser stopwatch.',
  'countdown-timer': 'Count down from a selected minute and second target.',
  'age-calculator': 'Calculate age from a birth date.',
  'business-day-calculator': 'Count weekdays between two dates.',
  'tip-calculator': 'Split a bill with tip across multiple people.',
  'discount-calculator': 'Calculate sale price and savings after a discount.',
  'salary-converter': 'Convert between hourly pay, weekly hours, and annual salary.',
  'fuel-cost-calculator': 'Estimate fuel cost from distance, efficiency, and fuel price.',
  'water-intake-calculator': 'Estimate daily water intake from body weight.',
  'calorie-calculator': 'Estimate basal metabolic rate from body details.',
  'bmi-water-calculator': 'Calculate BMI and recommended water intake together.',
  'grocery-list': 'Organize grocery items into a checkable list.',
  'meeting-notes': 'Generate a meeting-notes template from title and agenda.',
  'simple-notepad': 'Write quick notes directly in the browser.',
  'bar-chart-maker': 'Create a simple bar chart from labels and values.',
  'pie-chart-calculator': 'Calculate item percentages and pie-chart angles.',
}

function titleFromSlug(slug) {
  return slug
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

for (const categoryId of new Set([...existingTools, ...tools].map((tool) => tool.category))) {
  if (!categories.some((category) => category.id === categoryId)) {
    categories.push({id: categoryId, title: titleFromSlug(categoryId), icon: categoryIcons[categoryId] || '✨'})
  }
}

categories.forEach((category) => {
  category.title = categoryLabels[category.id] || titleFromSlug(category.id)
  category.icon = categoryIcons[category.id] || '✨'
})

for (const tool of [...existingTools, ...tools]) {
  tool.koTitle = tool.title
  tool.koDescription = tool.description
  tool.enTitle = toolTitles[tool.slug] || titleFromSlug(tool.slug)
  tool.enDescription = toolDescriptions[tool.slug] || 'Run this utility locally with browser-only inputs.'
  tool.title = toolTitles[tool.slug] || titleFromSlug(tool.slug)
  tool.description = toolDescriptions[tool.slug] || 'Run this utility locally with browser-only inputs.'
}

export const allTools = [...existingTools, ...tools]

export function getTool(slug) {
  return allTools.find((tool) => tool.slug === slug)
}

export function getDynamicTool(slug) {
  return tools.find((tool) => tool.slug === slug)
}

export function getToolsByCategory(categoryId) {
  return allTools.filter((tool) => tool.category === categoryId)
}
